// Curated dataset. Popularity values (0–100) are illustrative estimates of
// worldwide recognition, not measured statistics.

export const CATEGORIES = {
  vegetable: { label: 'Vegetables', color: '#7fa36b' },
  herb: { label: 'Herbs & Greens', color: '#4f9a72' },
  fruit: { label: 'Fruits', color: '#e08a63' },
  spice: { label: 'Spices & Chilies', color: '#c4743a' },
  meat: { label: 'Meat & Poultry', color: '#bf5656' },
  seafood: { label: 'Seafood', color: '#5a8fb8' },
  dairy: { label: 'Dairy & Eggs', color: '#e0bb57' },
  grain: { label: 'Grains & Starches', color: '#c39a62' },
  legume: { label: 'Legumes & Soy', color: '#958a4a' },
  nut: { label: 'Nuts & Seeds', color: '#9c7552' },
  pantry: { label: 'Sauces, Oils & Pantry', color: '#8d5f8e' },
};

export const CUISINES = {
  Italian: { country: 'Italy', region: 'Southern Europe', lat: 42.5, lng: 12.5, color: '#c0504d' },
  French: { country: 'France', region: 'Western Europe', lat: 46.6, lng: 2.4, color: '#5b7db1' },
  Spanish: { country: 'Spain', region: 'Southern Europe', lat: 40.2, lng: -3.7, color: '#d9913b' },
  Greek: { country: 'Greece', region: 'Southern Europe', lat: 39.0, lng: 22.0, color: '#4a90a8' },
  Mexican: { country: 'Mexico', region: 'North America', lat: 23.6, lng: -102.5, color: '#3f9a6b' },
  American: { country: 'United States', region: 'North America', lat: 39.8, lng: -98.6, color: '#8a6aa8' },
  Peruvian: { country: 'Peru', region: 'South America', lat: -9.2, lng: -75.0, color: '#d46a7e' },
  Brazilian: { country: 'Brazil', region: 'South America', lat: -14.2, lng: -51.9, color: '#6f9a3a' },
  Japanese: { country: 'Japan', region: 'East Asia', lat: 36.2, lng: 138.3, color: '#cf5f6f' },
  Chinese: { country: 'China', region: 'East Asia', lat: 35.9, lng: 104.2, color: '#b8433a' },
  Korean: { country: 'South Korea', region: 'East Asia', lat: 36.5, lng: 127.9, color: '#5a6fb0' },
  Thai: { country: 'Thailand', region: 'Southeast Asia', lat: 15.9, lng: 100.9, color: '#3e9c8f' },
  Vietnamese: { country: 'Vietnam', region: 'Southeast Asia', lat: 14.1, lng: 108.3, color: '#86a83f' },
  Indian: { country: 'India', region: 'South Asia', lat: 21.0, lng: 78.9, color: '#e0a030' },
  Levantine: { country: 'Lebanon', region: 'Middle East', lat: 33.9, lng: 35.9, color: '#b7884a' },
  Moroccan: { country: 'Morocco', region: 'North Africa', lat: 31.8, lng: -7.1, color: '#c8673e' },
  Ethiopian: { country: 'Ethiopia', region: 'East Africa', lat: 9.1, lng: 40.5, color: '#9e5a3c' },
  Turkish: { country: 'Turkey', region: 'Middle East', lat: 39.0, lng: 35.2, color: '#c14e5c' },
  Persian: { country: 'Iran', region: 'Middle East', lat: 32.4, lng: 53.7, color: '#7a6aa8' },
  Indonesian: { country: 'Indonesia', region: 'Southeast Asia', lat: -2.5, lng: 118.0, color: '#c27a3a' },
  Filipino: { country: 'Philippines', region: 'Southeast Asia', lat: 12.9, lng: 121.8, color: '#4d8fb0' },
  Jamaican: { country: 'Jamaica', region: 'Caribbean', lat: 18.1, lng: -77.3, color: '#2f9a5a' },
  'West African': { country: 'Nigeria', region: 'West Africa', lat: 9.1, lng: 8.7, color: '#d0852e' },
  Argentine: { country: 'Argentina', region: 'South America', lat: -38.4, lng: -63.6, color: '#6fa0c8' },
  German: { country: 'Germany', region: 'Central Europe', lat: 51.2, lng: 10.4, color: '#7d7a45' },
  Hungarian: { country: 'Hungary', region: 'Central Europe', lat: 47.2, lng: 19.5, color: '#b8452e' },
  British: { country: 'United Kingdom', region: 'Northern Europe', lat: 54.0, lng: -2.5, color: '#a05a6a' },
  Russian: { country: 'Russia', region: 'Eastern Europe', lat: 55.7, lng: 37.6, color: '#5a7a9a' },
  Swedish: { country: 'Sweden', region: 'Northern Europe', lat: 60.1, lng: 18.6, color: '#4a7ab0' },
  Polish: { country: 'Poland', region: 'Eastern Europe', lat: 51.9, lng: 19.1, color: '#c0475a' },
  Portuguese: { country: 'Portugal', region: 'Southern Europe', lat: 39.4, lng: -8.2, color: '#2f8a6a' },
  Cuban: { country: 'Cuba', region: 'Caribbean', lat: 21.5, lng: -77.8, color: '#d9703a' },
  Malaysian: { country: 'Malaysia', region: 'Southeast Asia', lat: 4.2, lng: 101.9, color: '#9a5aa0' },
  Georgian: { country: 'Georgia', region: 'Caucasus', lat: 42.3, lng: 43.4, color: '#a8406a' },
  'Sri Lankan': { country: 'Sri Lanka', region: 'South Asia', lat: 7.9, lng: 80.8, color: '#d4892a' },
  Colombian: { country: 'Colombia', region: 'South America', lat: 4.6, lng: -74.1, color: '#e0b030' },
  Hawaiian: { country: 'United States (Hawaii)', region: 'Pacific', lat: 20.8, lng: -156.3, color: '#3aa0a0' },
  Egyptian: { country: 'Egypt', region: 'North Africa', lat: 26.8, lng: 30.8, color: '#c9a040' },
  Irish: { country: 'Ireland', region: 'Northern Europe', lat: 53.4, lng: -8.2, color: '#3f8a4a' },
  Uzbek: { country: 'Uzbekistan', region: 'Central Asia', lat: 41.4, lng: 64.6, color: '#2f8aa8' },
  Burmese: { country: 'Myanmar', region: 'Southeast Asia', lat: 21.9, lng: 95.9, color: '#b8862a' },
  Nepali: { country: 'Nepal', region: 'South Asia', lat: 28.4, lng: 84.1, color: '#b04a4a' },
  'South African': { country: 'South Africa', region: 'Southern Africa', lat: -30.6, lng: 22.9, color: '#4a8a5a' },
  Canadian: { country: 'Canada', region: 'North America', lat: 56.1, lng: -106.3, color: '#b5303a' },
  Chilean: { country: 'Chile', region: 'South America', lat: -35.7, lng: -71.5, color: '#3a5aa8' },
};

const I = (category, ...names) => names.map((n) => [n, category]);
export const INGREDIENT_CATEGORY = Object.fromEntries([
  ...I('vegetable', 'tomato', 'onion', 'garlic', 'carrot', 'celery', 'potato', 'eggplant', 'zucchini',
    'bell pepper', 'mushroom', 'cucumber', 'cabbage', 'spinach', 'lettuce', 'scallion', 'sweet potato',
    'radish', 'bean sprouts', 'green beans', 'peas', 'fennel', 'bamboo shoot', 'olive', 'avocado', 'pickle', 'seaweed', 'beet', 'cassava', 'okra', 'shallot', 'kale', 'pumpkin'),
  ...I('herb', 'basil', 'parsley', 'cilantro', 'mint', 'dill', 'thyme', 'oregano', 'bay leaf',
    'lemongrass', 'curry leaves', 'pandan'),
  ...I('fruit', 'lemon', 'lime', 'orange', 'apple', 'pineapple', 'mango', 'papaya', 'pear',
    'pomegranate', 'apricot', 'coconut', 'tamarind', 'plantain', 'ackee', 'cherry', 'strawberry', 'lingonberry', 'grape', 'banana', 'jackfruit', 'raisins', 'blueberry'),
  ...I('spice', 'black pepper', 'chili', 'paprika', 'cumin', 'coriander', 'cinnamon', 'nutmeg',
    'saffron', 'turmeric', 'ginger', 'galangal', 'garam masala', 'cardamom', 'star anise',
    'sichuan pepper', 'five-spice', 'fenugreek', 'mustard seed', 'berbere', 'wasabi', 'vanilla',
    'caraway', 'sumac', 'allspice', 'cloves'),
  ...I('meat', 'beef', 'pork', 'chicken', 'lamb', 'veal', 'duck', 'bacon', 'guanciale', 'sausage', 'goat', 'ham'),
  ...I('seafood', 'fish', 'shrimp', 'shellfish', 'salmon', 'lobster'),
  ...I('dairy', 'egg', 'butter', 'milk', 'cream', 'parmesan', 'mozzarella', 'pecorino', 'mascarpone',
    'gruyère', 'feta', 'cheddar', 'queso fresco', 'yogurt', 'paneer', 'ghee', 'sour cream', 'cheese curds'),
  ...I('grain', 'flour', 'rice', 'pasta', 'noodles', 'bread', 'corn', 'flatbread', 'bulgur',
    'couscous', 'tapioca', 'yeast', 'rye', 'quinoa'),
  ...I('legume', 'chickpeas', 'lentils', 'beans', 'tofu', 'miso', 'soy sauce', 'black-eyed peas', 'fava beans'),
  ...I('nut', 'peanut', 'almond', 'walnut', 'pistachio', 'pine nuts', 'sesame', 'tahini', 'macadamia', 'pecan'),
  ...I('pantry', 'olive oil', 'vegetable oil', 'sesame oil', 'palm oil', 'salt', 'sugar', 'honey',
    'vinegar', 'white wine', 'red wine', 'stock', 'coffee', 'cocoa', 'chocolate', 'fish sauce',
    'hoisin', 'mirin', 'gochujang', 'chili bean paste', 'mayonnaise', 'coconut milk',
    'shrimp paste', 'dulce de leche', 'mustard', 'beer', 'maple syrup', 'tea'),
]);

// [dish, cuisine, popularity, ingredients, short note]
const D = [
  ['Margherita Pizza', 'Italian', 98, 'flour, yeast, tomato, mozzarella, basil, olive oil, salt', 'Naples, 1889 — the colours of the Italian flag.'],
  ['Spaghetti Carbonara', 'Italian', 92, 'pasta, egg, pecorino, guanciale, black pepper', 'A Roman classic; no cream required.'],
  ['Lasagna', 'Italian', 90, 'pasta, beef, tomato, onion, garlic, parmesan, mozzarella, milk, butter, flour', 'Layered pasta baked with ragù and béchamel.'],
  ['Risotto alla Milanese', 'Italian', 70, 'rice, saffron, butter, parmesan, onion, white wine, stock', 'Golden saffron risotto from Milan.'],
  ['Pesto Genovese', 'Italian', 78, 'basil, pine nuts, garlic, parmesan, pecorino, olive oil, pasta', 'Pounded basil sauce from Liguria.'],
  ['Tiramisu', 'Italian', 88, 'egg, sugar, mascarpone, coffee, cocoa, flour', 'Coffee-soaked layers of mascarpone cream.'],
  ['Minestrone', 'Italian', 60, 'tomato, onion, carrot, celery, beans, pasta, garlic, olive oil, zucchini, parmesan', 'A thick, seasonal vegetable soup.'],
  ['Osso Buco', 'Italian', 55, 'veal, onion, carrot, celery, white wine, tomato, garlic, lemon, parsley, butter', 'Braised veal shanks with gremolata.'],

  ['Coq au Vin', 'French', 65, 'chicken, red wine, mushroom, onion, bacon, garlic, thyme, butter, bay leaf', 'Chicken braised slowly in Burgundy wine.'],
  ['Ratatouille', 'French', 70, 'eggplant, zucchini, tomato, bell pepper, onion, garlic, olive oil, thyme, basil', 'Provençal summer vegetable stew.'],
  ['French Onion Soup', 'French', 72, 'onion, butter, stock, bread, gruyère, thyme, white wine, bay leaf', 'Caramelised onions under a bubbling cheese crust.'],
  ['Croissant', 'French', 90, 'flour, butter, yeast, sugar, milk, salt', 'Laminated, flaky, buttery pastry.'],
  ['Crème Brûlée', 'French', 80, 'cream, egg, sugar, vanilla', 'Silky custard beneath a glassy sugar crust.'],
  ['Bouillabaisse', 'French', 50, 'fish, shellfish, tomato, onion, garlic, saffron, fennel, olive oil, orange, bread', 'Marseille fisherman’s stew.'],
  ['Quiche Lorraine', 'French', 62, 'egg, cream, bacon, flour, butter, gruyère, nutmeg', 'Savoury custard tart from Lorraine.'],
  ['Beef Bourguignon', 'French', 68, 'beef, red wine, onion, carrot, mushroom, bacon, garlic, thyme, bay leaf', 'Beef stewed in red wine with pearl onions.'],

  ['Paella', 'Spanish', 85, 'rice, saffron, chicken, shrimp, tomato, bell pepper, paprika, olive oil, garlic, peas, green beans', 'Saffron rice cooked wide and shallow in Valencia.'],
  ['Gazpacho', 'Spanish', 60, 'tomato, cucumber, bell pepper, garlic, olive oil, bread, vinegar, salt', 'Chilled Andalusian tomato soup.'],
  ['Tortilla Española', 'Spanish', 70, 'potato, egg, onion, olive oil, salt', 'Thick potato and egg omelette.'],
  ['Patatas Bravas', 'Spanish', 66, 'potato, paprika, tomato, garlic, olive oil, chili, mayonnaise', 'Crisp potatoes with a smoky, spicy sauce.'],
  ['Churros con Chocolate', 'Spanish', 75, 'flour, sugar, vegetable oil, cinnamon, chocolate, milk, salt', 'Fried dough dipped in thick hot chocolate.'],

  ['Moussaka', 'Greek', 64, 'eggplant, lamb, tomato, onion, garlic, cinnamon, milk, butter, flour, nutmeg, egg', 'Layers of eggplant, spiced lamb and béchamel.'],
  ['Greek Salad', 'Greek', 72, 'tomato, cucumber, onion, olive, feta, oregano, olive oil, bell pepper', 'Horiatiki — the village salad.'],
  ['Souvlaki', 'Greek', 70, 'pork, garlic, lemon, oregano, olive oil, flatbread, yogurt, tomato, onion', 'Grilled skewers wrapped in warm pita.'],
  ['Spanakopita', 'Greek', 55, 'spinach, feta, flour, onion, dill, egg, olive oil, butter', 'Spinach and feta in crisp phyllo.'],
  ['Tzatziki', 'Greek', 60, 'yogurt, cucumber, garlic, dill, olive oil, lemon', 'Cool yogurt and cucumber dip.'],

  ['Tacos al Pastor', 'Mexican', 88, 'pork, pineapple, chili, onion, cilantro, corn, lime, garlic, cumin, vinegar', 'Spit-roasted pork, born from Lebanese shawarma.'],
  ['Guacamole', 'Mexican', 85, 'avocado, lime, onion, cilantro, chili, tomato, salt', 'Aztec-era avocado sauce.'],
  ['Mole Poblano', 'Mexican', 58, 'chili, chocolate, sesame, almond, garlic, onion, cinnamon, tomato, chicken, cumin', 'Dozens of ingredients ground into a dark, rich sauce.'],
  ['Enchiladas', 'Mexican', 74, 'corn, chicken, chili, tomato, onion, queso fresco, cream, garlic', 'Rolled tortillas bathed in chili sauce.'],
  ['Pozole', 'Mexican', 52, 'pork, corn, chili, garlic, onion, oregano, cabbage, lime, radish', 'Hominy stew served for celebrations.'],
  ['Chiles en Nogada', 'Mexican', 40, 'chili, pork, walnut, pomegranate, cream, apple, onion, garlic, parsley', 'Stuffed poblanos in walnut sauce.'],

  ['Hamburger', 'American', 96, 'beef, bread, lettuce, tomato, onion, cheddar, pickle, salt', 'The world’s favourite sandwich.'],
  ['BBQ Ribs', 'American', 70, 'pork, sugar, paprika, garlic, vinegar, tomato, black pepper, salt', 'Low-and-slow smoked ribs.'],
  ['Mac and Cheese', 'American', 80, 'pasta, cheddar, milk, butter, flour, salt', 'Comfort food baked until golden.'],
  ['Fried Chicken', 'American', 86, 'chicken, flour, milk, paprika, black pepper, vegetable oil, garlic, salt', 'Buttermilk-brined, crisp-fried.'],
  ['Apple Pie', 'American', 76, 'apple, flour, butter, sugar, cinnamon, nutmeg, lemon', 'As American as…'],
  ['Clam Chowder', 'American', 55, 'shellfish, potato, onion, celery, cream, bacon, butter, thyme', 'New England’s creamy clam soup.'],

  ['Ceviche', 'Peruvian', 78, 'fish, lime, chili, onion, cilantro, sweet potato, corn, salt', 'Raw fish cured in tiger’s milk.'],
  ['Lomo Saltado', 'Peruvian', 60, 'beef, potato, tomato, onion, soy sauce, vinegar, chili, rice, cilantro', 'Chifa stir-fry of beef and fries.'],
  ['Ají de Gallina', 'Peruvian', 45, 'chicken, chili, bread, milk, walnut, onion, garlic, parmesan, rice', 'Shredded chicken in a creamy yellow-pepper sauce.'],

  ['Feijoada', 'Brazilian', 62, 'beans, pork, sausage, onion, garlic, bay leaf, orange, rice, bacon', 'Black bean and pork stew.'],
  ['Pão de Queijo', 'Brazilian', 58, 'tapioca, parmesan, egg, milk, vegetable oil, salt', 'Chewy cheese bread from Minas Gerais.'],
  ['Moqueca', 'Brazilian', 50, 'fish, coconut milk, tomato, onion, bell pepper, cilantro, lime, palm oil, garlic', 'Bahian fish stew with dendê oil.'],

  ['Sushi', 'Japanese', 97, 'rice, fish, vinegar, seaweed, soy sauce, wasabi, ginger, sugar', 'Vinegared rice with the freshest fish.'],
  ['Ramen', 'Japanese', 92, 'noodles, pork, egg, soy sauce, miso, scallion, garlic, ginger, seaweed, stock', 'Noodles in a deep, slow-simmered broth.'],
  ['Tempura', 'Japanese', 70, 'shrimp, flour, egg, vegetable oil, sweet potato, soy sauce, radish, mirin', 'Feather-light battered fritters.'],
  ['Miso Soup', 'Japanese', 75, 'miso, tofu, seaweed, scallion, fish', 'Everyday soup of dashi and miso.'],
  ['Teriyaki Chicken', 'Japanese', 72, 'chicken, soy sauce, mirin, sugar, ginger, garlic, rice', 'Glossy, sweet-savoury glaze.'],
  ['Okonomiyaki', 'Japanese', 45, 'flour, cabbage, egg, pork, scallion, mayonnaise, seaweed', 'Savory pancake, "grilled as you like it".'],

  ['Kung Pao Chicken', 'Chinese', 80, 'chicken, peanut, chili, sichuan pepper, soy sauce, garlic, ginger, scallion, vinegar, sugar', 'Sichuan stir-fry with numbing heat.'],
  ['Mapo Tofu', 'Chinese', 68, 'tofu, pork, chili, sichuan pepper, chili bean paste, garlic, ginger, scallion, soy sauce', 'Silken tofu in fiery bean sauce.'],
  ['Peking Duck', 'Chinese', 75, 'duck, hoisin, scallion, cucumber, flour, five-spice, sugar', 'Lacquered roast duck in thin pancakes.'],
  ['Jiaozi Dumplings', 'Chinese', 88, 'flour, pork, cabbage, ginger, scallion, soy sauce, sesame oil, garlic', 'Folded for Lunar New Year.'],
  ['Fried Rice', 'Chinese', 85, 'rice, egg, scallion, soy sauce, garlic, peas, carrot, sesame oil', 'Day-old rice, wok-tossed.'],
  ['Hot and Sour Soup', 'Chinese', 55, 'tofu, mushroom, egg, vinegar, black pepper, soy sauce, bamboo shoot', 'Peppery, tangy and warming.'],

  ['Pad Thai', 'Thai', 92, 'noodles, shrimp, egg, tofu, peanut, fish sauce, tamarind, lime, bean sprouts, garlic, sugar', 'Stir-fried rice noodles, sweet-sour-salty.'],
  ['Green Curry', 'Thai', 80, 'coconut milk, chicken, chili, lemongrass, galangal, basil, fish sauce, eggplant, lime, sugar', 'Fragrant curry of fresh green chilies.'],
  ['Tom Yum', 'Thai', 74, 'shrimp, lemongrass, galangal, lime, chili, fish sauce, mushroom, cilantro', 'Hot and sour shrimp soup.'],
  ['Som Tam', 'Thai', 58, 'papaya, chili, lime, fish sauce, peanut, tomato, garlic, green beans, sugar', 'Pounded green papaya salad.'],
  ['Mango Sticky Rice', 'Thai', 70, 'rice, mango, coconut milk, sugar, sesame, salt', 'Sweet coconut rice with ripe mango.'],

  ['Pho', 'Vietnamese', 88, 'noodles, beef, star anise, cinnamon, ginger, onion, fish sauce, basil, cilantro, lime, bean sprouts, chili', 'Aromatic beef noodle soup.'],
  ['Bánh Mì', 'Vietnamese', 80, 'bread, pork, carrot, radish, cilantro, cucumber, chili, mayonnaise, soy sauce', 'French baguette, Vietnamese fillings.'],
  ['Gỏi Cuốn', 'Vietnamese', 64, 'rice, shrimp, pork, lettuce, mint, noodles, peanut, hoisin', 'Fresh summer rolls in rice paper.'],

  ['Kimchi', 'Korean', 76, 'cabbage, chili, garlic, ginger, fish sauce, scallion, radish, sugar', 'Fermented napa cabbage.'],
  ['Bibimbap', 'Korean', 78, 'rice, beef, egg, spinach, carrot, bean sprouts, gochujang, sesame oil, mushroom, garlic', 'Mixed rice in a sizzling stone bowl.'],
  ['Bulgogi', 'Korean', 74, 'beef, soy sauce, pear, garlic, sesame oil, sugar, scallion, ginger', '"Fire meat" — marinated grilled beef.'],
  ['Tteokbokki', 'Korean', 60, 'rice, gochujang, fish, scallion, sugar, egg, cabbage', 'Chewy rice cakes in red chili sauce.'],

  ['Butter Chicken', 'Indian', 90, 'chicken, tomato, butter, cream, garam masala, ginger, garlic, chili, yogurt, fenugreek', 'Murgh makhani, born in Delhi.'],
  ['Biryani', 'Indian', 88, 'rice, chicken, yogurt, onion, saffron, garam masala, ginger, garlic, mint, cilantro, ghee, cardamom', 'Layered, perfumed rice.'],
  ['Chana Masala', 'Indian', 72, 'chickpeas, tomato, onion, garlic, ginger, cumin, coriander, garam masala, chili', 'Spiced chickpea curry.'],
  ['Palak Paneer', 'Indian', 70, 'spinach, paneer, onion, garlic, ginger, cumin, cream, garam masala, chili', 'Fresh cheese in spinach gravy.'],
  ['Dal Tadka', 'Indian', 75, 'lentils, turmeric, cumin, garlic, ginger, onion, tomato, ghee, chili', 'Lentils finished with sizzling spices.'],
  ['Samosa', 'Indian', 82, 'flour, potato, peas, cumin, coriander, chili, ginger, vegetable oil', 'Crisp pastry pockets of spiced potato.'],
  ['Masala Dosa', 'Indian', 68, 'rice, lentils, potato, mustard seed, turmeric, onion, chili, curry leaves, coconut', 'Crisp fermented crêpe from the South.'],

  ['Hummus', 'Levantine', 88, 'chickpeas, tahini, lemon, garlic, olive oil, cumin, salt', 'Creamy chickpea and sesame purée.'],
  ['Falafel', 'Levantine', 82, 'chickpeas, onion, garlic, parsley, cilantro, cumin, coriander, vegetable oil', 'Herb-flecked chickpea fritters.'],
  ['Shawarma', 'Levantine', 85, 'chicken, garlic, yogurt, lemon, cumin, paprika, turmeric, flatbread, tahini', 'Spit-roasted meat shaved thin.'],
  ['Tabbouleh', 'Levantine', 60, 'bulgur, parsley, mint, tomato, onion, lemon, olive oil', 'A parsley salad, not a grain salad.'],
  ['Baklava', 'Levantine', 74, 'flour, walnut, pistachio, butter, honey, sugar, cinnamon', 'Honeyed layers of nuts and phyllo.'],

  ['Lamb Tagine', 'Moroccan', 66, 'lamb, onion, garlic, ginger, cinnamon, cumin, saffron, apricot, almond, honey, olive oil', 'Slow-cooked under a conical lid.'],
  ['Vegetable Couscous', 'Moroccan', 62, 'couscous, carrot, zucchini, chickpeas, onion, tomato, cumin, cinnamon, turmeric', 'Friday couscous with seven vegetables.'],
  ['Harira', 'Moroccan', 45, 'lentils, chickpeas, tomato, onion, celery, cilantro, parsley, lamb, ginger, cinnamon, turmeric', 'Soup that breaks the Ramadan fast.'],

  ['Doro Wat', 'Ethiopian', 50, 'chicken, onion, berbere, butter, garlic, ginger, egg, cardamom', 'Slow-simmered chicken in berbere.'],
  ['Misir Wat', 'Ethiopian', 45, 'lentils, berbere, onion, garlic, ginger, tomato, vegetable oil', 'Spiced red lentil stew.'],
  ['Shiro', 'Ethiopian', 42, 'chickpeas, berbere, onion, garlic, tomato, butter', 'Silky ground-chickpea stew.'],
  ['Kitfo', 'Ethiopian', 40, 'beef, butter, berbere, cardamom, chili', 'Minced beef warmed in spiced butter.'],

  // existing cuisines, more dishes
  ['Arancini', 'Italian', 72, 'rice, mozzarella, peas, beef, egg, bread, tomato, parmesan', 'Sicilian fried rice balls with a molten heart.'],
  ['Panna Cotta', 'Italian', 68, 'cream, milk, sugar, vanilla, strawberry', 'Cooked cream, barely set.'],
  ['Salade Niçoise', 'French', 58, 'fish, egg, potato, green beans, olive, tomato, lettuce, olive oil, vinegar, mustard', 'The composed salad of Nice.'],
  ['Crêpes', 'French', 82, 'flour, milk, egg, butter, sugar, salt', 'Paper-thin Breton pancakes.'],
  ['Crema Catalana', 'Spanish', 52, 'milk, egg, sugar, cinnamon, lemon', 'Catalonia’s citrus-scented custard.'],
  ['Avgolemono', 'Greek', 48, 'chicken, rice, egg, lemon, stock, dill', 'Silky egg-lemon soup.'],
  ['Chilaquiles', 'Mexican', 62, 'corn, chili, tomato, onion, queso fresco, cream, egg, cilantro', 'Tortilla chips simmered in salsa for breakfast.'],
  ['Pancakes', 'American', 84, 'flour, milk, egg, butter, sugar, maple syrup', 'Fluffy stacks under maple syrup.'],
  ['Causa Limeña', 'Peruvian', 44, 'potato, chili, lime, chicken, avocado, mayonnaise, egg', 'Layered terrine of chili-spiked potato.'],
  ['Brigadeiro', 'Brazilian', 60, 'cocoa, sugar, butter, milk', 'Fudgy chocolate truffles for every party.'],
  ['Tonkatsu', 'Japanese', 70, 'pork, flour, egg, bread, cabbage, rice, vegetable oil', 'Panko-crusted pork cutlet.'],
  ['Char Siu', 'Chinese', 72, 'pork, hoisin, honey, soy sauce, five-spice, garlic, sugar', 'Cantonese barbecued pork.'],
  ['Massaman Curry', 'Thai', 76, 'beef, coconut milk, potato, peanut, onion, cinnamon, cardamom, tamarind, fish sauce, chili', 'A Persian-influenced, gently spiced curry.'],
  ['Bún Chả', 'Vietnamese', 62, 'pork, noodles, fish sauce, sugar, garlic, lettuce, mint, lime, chili, vinegar', 'Grilled pork with noodles and herbs, Hanoi style.'],
  ['Japchae', 'Korean', 64, 'noodles, beef, spinach, carrot, mushroom, onion, soy sauce, sesame oil, sugar, garlic', 'Glass noodles stir-fried with vegetables.'],
  ['Rogan Josh', 'Indian', 70, 'lamb, yogurt, chili, garlic, ginger, cardamom, cinnamon, onion, garam masala', 'Kashmiri lamb in a deep red gravy.'],
  ['Shakshuka', 'Levantine', 78, 'egg, tomato, bell pepper, onion, garlic, cumin, paprika, chili, olive oil', 'Eggs poached in spiced tomato.'],
  ['Chicken Pastilla', 'Moroccan', 44, 'chicken, flour, almond, egg, onion, cinnamon, saffron, sugar, butter, parsley', 'Sweet-savoury pie dusted with cinnamon sugar.'],

  ['Adana Kebab', 'Turkish', 70, 'lamb, chili, onion, flatbread, sumac, parsley, tomato, salt', 'Hand-minced lamb on wide skewers.'],
  ['Menemen', 'Turkish', 56, 'egg, tomato, bell pepper, onion, olive oil, chili', 'Soft-scrambled eggs with peppers and tomato.'],
  ['İmam Bayıldı', 'Turkish', 48, 'eggplant, onion, tomato, garlic, olive oil, parsley, sugar', '"The imam fainted" — olive-oil braised eggplant.'],
  ['Lahmacun', 'Turkish', 62, 'flour, yeast, lamb, onion, tomato, bell pepper, parsley, sumac, lemon, chili', 'Thin flatbread with spiced lamb.'],
  ['Turkish Coffee', 'Turkish', 58, 'coffee, sugar, cardamom', 'Unfiltered and thick, read from the grounds.'],

  ['Ghormeh Sabzi', 'Persian', 56, 'lamb, beans, parsley, cilantro, fenugreek, onion, lime, turmeric', 'Iran’s beloved herb stew.'],
  ['Fesenjan', 'Persian', 48, 'chicken, walnut, pomegranate, onion, turmeric, cinnamon, sugar', 'Walnut and pomegranate braise.'],
  ['Tahdig', 'Persian', 54, 'rice, butter, saffron, yogurt, vegetable oil', 'The prized golden crust of the rice pot.'],
  ['Kuku Sabzi', 'Persian', 40, 'egg, parsley, cilantro, dill, walnut, turmeric, onion', 'A frittata that is mostly herbs.'],
  ['Joojeh Kabab', 'Persian', 52, 'chicken, saffron, lemon, onion, yogurt, butter', 'Saffron chicken skewers.'],

  ['Nasi Goreng', 'Indonesian', 80, 'rice, egg, shallot, garlic, chili, soy sauce, shrimp paste, shrimp, cucumber', 'Sweet-soy fried rice.'],
  ['Rendang', 'Indonesian', 78, 'beef, coconut milk, lemongrass, galangal, ginger, chili, shallot, garlic, turmeric, coconut', 'Beef slow-cooked until the coconut caramelises.'],
  ['Satay', 'Indonesian', 76, 'chicken, peanut, soy sauce, garlic, shallot, coriander, turmeric, lime, sugar, chili', 'Skewers with peanut sauce.'],
  ['Gado-Gado', 'Indonesian', 54, 'cabbage, bean sprouts, potato, egg, tofu, peanut, chili, lime, green beans, cucumber', 'Vegetable salad in peanut dressing.'],

  ['Chicken Adobo', 'Filipino', 74, 'chicken, pork, vinegar, soy sauce, garlic, bay leaf, black pepper', 'Braised in vinegar and soy — the national dish.'],
  ['Sinigang', 'Filipino', 56, 'pork, tamarind, tomato, radish, onion, green beans, spinach, chili, fish sauce', 'Sour tamarind soup.'],
  ['Lumpia', 'Filipino', 62, 'flour, pork, carrot, cabbage, onion, garlic, soy sauce, vegetable oil', 'Crisp, slender spring rolls.'],
  ['Pancit', 'Filipino', 58, 'noodles, chicken, cabbage, carrot, soy sauce, garlic, onion, lime', 'Birthday noodles for long life.'],
  ['Lechon', 'Filipino', 60, 'pork, garlic, lemongrass, salt, black pepper, bay leaf', 'Whole spit-roasted pig.'],

  ['Jerk Chicken', 'Jamaican', 80, 'chicken, allspice, chili, scallion, thyme, garlic, ginger, lime, soy sauce, sugar, cinnamon, nutmeg', 'Smoky, fiery and fragrant with pimento.'],
  ['Ackee and Saltfish', 'Jamaican', 52, 'ackee, fish, onion, tomato, chili, bell pepper, thyme, black pepper', 'Jamaica’s national breakfast.'],
  ['Rice and Peas', 'Jamaican', 60, 'rice, beans, coconut milk, scallion, thyme, allspice, garlic, chili', 'Kidney beans and rice in coconut milk.'],
  ['Curry Goat', 'Jamaican', 56, 'goat, turmeric, cumin, coriander, potato, onion, garlic, chili, thyme, allspice', 'Sunday curry, slow and rich.'],
  ['Fried Plantain', 'Jamaican', 58, 'plantain, vegetable oil, salt', 'Sweet, caramel-edged ripe plantain.'],

  ['Jollof Rice', 'West African', 78, 'rice, tomato, bell pepper, onion, chili, vegetable oil, thyme, bay leaf, stock', 'Party rice — and the subject of friendly rivalry.'],
  ['Egusi Soup', 'West African', 50, 'spinach, palm oil, fish, beef, onion, chili, stock, shrimp', 'Leafy soup thickened with melon seeds.'],
  ['Suya', 'West African', 62, 'beef, peanut, chili, ginger, garlic, onion, paprika', 'Spice-crusted grilled skewers.'],
  ['Puff-Puff', 'West African', 54, 'flour, yeast, sugar, nutmeg, vegetable oil', 'Pillowy fried dough balls.'],
  ['Akara', 'West African', 46, 'black-eyed peas, onion, chili, salt, vegetable oil', 'Bean fritters for breakfast.'],
  ['Fufu and Okra Soup', 'West African', 48, 'cassava, okra, palm oil, fish, onion, chili, stock', 'Pounded cassava with silky okra soup.'],

  ['Asado', 'Argentine', 74, 'beef, sausage, salt, black pepper, parsley, garlic, oregano, vinegar, chili, olive oil', 'The ritual of the grill, with chimichurri.'],
  ['Empanadas', 'Argentine', 78, 'flour, beef, onion, egg, olive, cumin, paprika, butter', 'Hand pies, crimped by region.'],
  ['Milanesa', 'Argentine', 64, 'beef, bread, egg, garlic, parsley, lemon, vegetable oil', 'Breaded cutlet, an Italian import.'],
  ['Alfajores', 'Argentine', 66, 'flour, butter, sugar, egg, dulce de leche, coconut', 'Sandwich cookies filled with dulce de leche.'],

  ['Wiener Schnitzel', 'German', 76, 'veal, flour, egg, bread, lemon, butter, salt', 'Thin, golden, breaded veal.'],
  ['Sauerbraten', 'German', 50, 'beef, vinegar, red wine, onion, carrot, bay leaf, sugar, allspice', 'Pot roast marinated for days.'],
  ['Kartoffelsalat', 'German', 56, 'potato, onion, vinegar, mustard, stock, bacon, vegetable oil', 'Warm potato salad, Swabian style.'],
  ['Bratwurst', 'German', 70, 'sausage, mustard, bread, onion, caraway', 'Grilled sausage with mustard.'],
  ['Black Forest Cake', 'German', 64, 'flour, cocoa, egg, sugar, cherry, cream, butter', 'Chocolate, cherries and clouds of cream.'],

  ['Goulash', 'Hungarian', 72, 'beef, paprika, onion, potato, carrot, caraway, tomato, bell pepper, garlic', 'The herdsman’s paprika soup.'],
  ['Chicken Paprikash', 'Hungarian', 58, 'chicken, paprika, onion, sour cream, flour, butter, bell pepper', 'Chicken in a creamy paprika sauce.'],
  ['Lángos', 'Hungarian', 50, 'flour, yeast, garlic, sour cream, cheddar, milk, vegetable oil', 'Fried dough with garlic, sour cream and cheese.'],

  ['Fish and Chips', 'British', 82, 'fish, potato, flour, beer, vegetable oil, salt, vinegar, peas', 'Seaside supper wrapped in paper.'],
  ['Shepherd’s Pie', 'British', 66, 'lamb, potato, onion, carrot, peas, butter, milk, stock, thyme', 'Lamb mince under mashed potato.'],
  ['Full English Breakfast', 'British', 70, 'egg, bacon, sausage, beans, tomato, mushroom, bread, butter', 'The fry-up.'],
  ['Scones', 'British', 62, 'flour, butter, milk, sugar, egg, strawberry, cream', 'With jam and clotted cream, in that order (or not).'],

  ['Borscht', 'Russian', 66, 'beet, cabbage, potato, carrot, onion, dill, sour cream, beef, vinegar', 'Ruby beet soup.'],
  ['Beef Stroganoff', 'Russian', 72, 'beef, mushroom, onion, sour cream, butter, mustard, noodles', 'Seared beef in mustard sour cream.'],
  ['Pelmeni', 'Russian', 60, 'flour, egg, pork, beef, onion, sour cream, black pepper', 'Siberian dumplings, frozen by the hundred.'],
  ['Blini', 'Russian', 58, 'flour, milk, egg, butter, yeast, sour cream, fish', 'Yeasted pancakes for Maslenitsa.'],

  ['Tibs', 'Ethiopian', 52, 'beef, onion, thyme, chili, butter, garlic, bell pepper', 'Sizzling sautéed beef, served to honour guests.'],
  ['Gomen', 'Ethiopian', 38, 'kale, onion, garlic, ginger, butter, chili', 'Collard-style greens in spiced butter.'],
  ['Zaalouk', 'Moroccan', 46, 'eggplant, tomato, garlic, cumin, paprika, olive oil, cilantro', 'Smoky eggplant and tomato salad.'],
  ['Kefta Tagine', 'Moroccan', 56, 'beef, egg, tomato, onion, cumin, paprika, cilantro, parsley', 'Meatballs and eggs in tomato sauce.'],

  ['Swedish Meatballs', 'Swedish', 74, 'beef, pork, onion, bread, milk, egg, allspice, cream, lingonberry, potato', 'Köttbullar with lingonberries and cream sauce.'],
  ['Gravlax', 'Swedish', 58, 'salmon, dill, sugar, salt, black pepper', 'Salmon cured under dill.'],
  ['Kanelbullar', 'Swedish', 66, 'flour, butter, sugar, cinnamon, cardamom, yeast, milk', 'Cardamom-scented cinnamon buns for fika.'],
  ['Jansson’s Temptation', 'Swedish', 40, 'potato, onion, cream, fish, bread', 'Potato and sprat gratin at Christmas.'],

  ['Pierogi', 'Polish', 74, 'flour, egg, potato, onion, sour cream, butter', 'Half-moon dumplings, boiled then fried.'],
  ['Bigos', 'Polish', 50, 'cabbage, sausage, pork, mushroom, onion, tomato, bay leaf, allspice, red wine', 'Hunter’s stew of cabbage and meats.'],
  ['Żurek', 'Polish', 44, 'rye, sausage, egg, potato, garlic, oregano', 'Sour rye soup, often served in bread.'],
  ['Gołąbki', 'Polish', 48, 'cabbage, beef, rice, onion, tomato', 'Cabbage rolls in tomato sauce.'],

  ['Bacalhau à Brás', 'Portuguese', 54, 'fish, potato, egg, onion, olive, parsley, olive oil', 'Salt cod scrambled with matchstick potatoes.'],
  ['Pastel de Nata', 'Portuguese', 84, 'flour, egg, sugar, cream, cinnamon, lemon, butter', 'Blistered custard tarts from Belém.'],
  ['Caldo Verde', 'Portuguese', 52, 'kale, potato, onion, sausage, olive oil, garlic', 'Green kale soup with chouriço.'],
  ['Francesinha', 'Portuguese', 50, 'bread, beef, ham, sausage, cheddar, beer, tomato, egg', 'Porto’s gloriously excessive sandwich.'],
  ['Piri-Piri Chicken', 'Portuguese', 70, 'chicken, chili, garlic, lemon, paprika, olive oil, oregano', 'Flame-grilled bird with African bird’s-eye chili.'],

  ['Cubano', 'Cuban', 70, 'bread, pork, ham, gruyère, pickle, mustard, butter', 'Pressed sandwich born between Havana and Tampa.'],
  ['Ropa Vieja', 'Cuban', 64, 'beef, bell pepper, onion, tomato, garlic, cumin, olive, white wine', '"Old clothes" — shredded braised beef.'],
  ['Moros y Cristianos', 'Cuban', 52, 'beans, rice, onion, bell pepper, garlic, cumin, bay leaf', 'Black beans and white rice cooked together.'],
  ['Lechón Asado', 'Cuban', 56, 'pork, orange, lime, garlic, oregano, cumin', 'Roast pork in sour-orange mojo.'],

  ['Nasi Lemak', 'Malaysian', 76, 'rice, coconut milk, pandan, fish, peanut, cucumber, egg, chili, shrimp paste', 'Coconut rice with sambal — the national breakfast.'],
  ['Laksa', 'Malaysian', 78, 'noodles, coconut milk, shrimp, tofu, lemongrass, chili, shrimp paste, bean sprouts, egg', 'Spicy coconut noodle soup.'],
  ['Roti Canai', 'Malaysian', 68, 'flour, ghee, egg, sugar, salt', 'Flaky griddled flatbread with curry.'],
  ['Char Kway Teow', 'Malaysian', 66, 'noodles, shrimp, egg, bean sprouts, soy sauce, chili, garlic, scallion, sausage', 'Smoky wok-fried flat noodles.'],
  ['Kaya Toast', 'Malaysian', 54, 'bread, coconut milk, egg, sugar, pandan, butter', 'Coconut jam toast with soft eggs.'],

  ['Samgyeopsal', 'Korean', 70, 'pork, garlic, lettuce, gochujang, sesame oil, cabbage, chili', 'Grilled pork belly wrapped in lettuce.'],
  ['Yakitori', 'Japanese', 72, 'chicken, scallion, soy sauce, mirin, sugar', 'Charcoal-grilled chicken skewers.'],
  ['Elote', 'Mexican', 70, 'corn, mayonnaise, queso fresco, chili, lime', 'Street corn slathered and dusted with chili.'],
  ['Gulab Jamun', 'Indian', 74, 'milk, flour, sugar, cardamom, ghee, saffron', 'Milk dumplings soaked in fragrant syrup.'],

  ['Khachapuri', 'Georgian', 72, 'flour, yeast, mozzarella, feta, egg, butter', 'Cheese-filled bread boat crowned with an egg.'],
  ['Khinkali', 'Georgian', 62, 'flour, beef, pork, onion, cilantro, black pepper, cumin', 'Twisted soup dumplings, eaten by the knot.'],
  ['Pkhali', 'Georgian', 42, 'spinach, beet, walnut, garlic, cilantro, pomegranate, coriander', 'Vegetable and walnut pâtés.'],
  ['Chakhokhbili', 'Georgian', 44, 'chicken, tomato, onion, garlic, cilantro, basil, fenugreek, chili', 'Herby chicken and tomato stew.'],
  ['Churchkhela', 'Georgian', 40, 'grape, walnut, flour', 'Walnuts dipped in thickened grape must.'],

  ['Hoppers', 'Sri Lankan', 58, 'rice, coconut milk, yeast, sugar, egg', 'Bowl-shaped crêpes with crisp lacy edges.'],
  ['Kottu Roti', 'Sri Lankan', 62, 'flour, egg, carrot, cabbage, onion, chili, curry leaves, chicken, soy sauce', 'Chopped flatbread stir-fry, clattered on a griddle.'],
  ['Fish Ambul Thiyal', 'Sri Lankan', 44, 'fish, tamarind, black pepper, curry leaves, garlic, cinnamon, cloves', 'Sour, peppery fish curry.'],
  ['Parippu', 'Sri Lankan', 52, 'lentils, coconut milk, turmeric, curry leaves, mustard seed, onion, chili', 'Creamy coconut dhal.'],
  ['Pol Sambol', 'Sri Lankan', 48, 'coconut, chili, lime, onion, fish', 'Fresh coconut relish.'],
  ['Pumpkin Curry', 'Sri Lankan', 46, 'pumpkin, coconut milk, turmeric, curry leaves, mustard seed, garlic, cinnamon, chili', 'Golden pumpkin simmered in coconut.'],
  ['Polos Curry', 'Sri Lankan', 40, 'jackfruit, coconut milk, chili, curry leaves, cinnamon, cloves, garlic, mustard seed', 'Young jackfruit curry.'],

  ['Bandeja Paisa', 'Colombian', 60, 'beans, rice, pork, beef, sausage, egg, plantain, avocado, corn', 'A platter big enough for a mule driver.'],
  ['Arepas', 'Colombian', 74, 'corn, butter, queso fresco, salt', 'Griddled corn cakes, split and filled.'],
  ['Ajiaco', 'Colombian', 54, 'chicken, potato, corn, oregano, cream, avocado', 'Bogotá’s three-potato chicken soup.'],
  ['Sancocho', 'Colombian', 52, 'chicken, plantain, cassava, corn, potato, cilantro, onion, garlic', 'Hearty Sunday stew.'],

  ['Poke', 'Hawaiian', 76, 'fish, soy sauce, sesame oil, seaweed, scallion, sesame, chili', 'Cubed raw fish, dressed simply.'],
  ['Loco Moco', 'Hawaiian', 56, 'rice, beef, egg, onion, mushroom, stock, soy sauce', 'Rice, burger patty, fried egg and gravy.'],
  ['Kalua Pig', 'Hawaiian', 52, 'pork, salt', 'Whole pig steamed in an underground imu.'],
  ['Spam Musubi', 'Hawaiian', 58, 'rice, ham, seaweed, soy sauce, sugar', 'Glazed luncheon meat on rice, wrapped in nori.'],
  ['Huli Huli Chicken', 'Hawaiian', 54, 'chicken, pineapple, soy sauce, ginger, garlic, sugar, tomato', 'Turned-and-turned teriyaki-style grilled chicken.'],
  ['Banana Macadamia Bread', 'Hawaiian', 50, 'banana, flour, sugar, butter, egg, macadamia', 'Island banana bread with buttery nuts.'],

  ['Koshari', 'Egyptian', 66, 'rice, lentils, pasta, chickpeas, tomato, onion, vinegar, garlic, cumin, chili', 'Cairo’s carb-on-carb street feast.'],
  ['Ful Medames', 'Egyptian', 62, 'fava beans, olive oil, cumin, garlic, lemon, parsley', 'Slow-stewed fava beans for breakfast.'],
  ['Molokhia', 'Egyptian', 44, 'spinach, chicken, garlic, coriander, stock', 'Silky green soup of jute leaves.'],
  ['Ta’ameya', 'Egyptian', 56, 'fava beans, parsley, cilantro, dill, onion, garlic, cumin, sesame', 'Egypt’s green fava-bean falafel.'],
  ['Fattah', 'Egyptian', 42, 'rice, flatbread, lamb, garlic, vinegar, tomato', 'Feast-day layers of bread, rice and meat.'],

  ['Irish Stew', 'Irish', 64, 'lamb, potato, onion, carrot, thyme, stock, parsley', 'Mutton, potatoes and patience.'],
  ['Colcannon', 'Irish', 50, 'potato, kale, butter, milk, scallion', 'Buttery mash with greens.'],
  ['Soda Bread', 'Irish', 56, 'flour, milk, salt, butter', 'Quick bread marked with a cross.'],
  ['Boxty', 'Irish', 40, 'potato, flour, milk, egg, butter', 'Potato pancakes from the north-west.'],
  ['Beef and Stout Stew', 'Irish', 60, 'beef, beer, onion, carrot, potato, thyme, tomato', 'Beef braised dark and rich in stout.'],

  ['Masala Chai', 'Indian', 80, 'tea, milk, sugar, ginger, cardamom, cinnamon, cloves, black pepper', 'Spiced milky tea from every street corner.'],
  ['Pecan Pie', 'American', 66, 'pecan, sugar, butter, egg, maple syrup, vanilla, flour', 'Southern holiday pie with a gooey heart.'],
  ['Lobster Roll', 'American', 64, 'lobster, bread, mayonnaise, butter, celery, lemon', 'New England summer in a toasted bun.'],
  ['Solterito', 'Peruvian', 40, 'fava beans, corn, queso fresco, tomato, onion, olive, chili, lime', 'Arequipa’s bright bean and cheese salad.'],
  ['Quinoa Soup', 'Peruvian', 44, 'quinoa, potato, carrot, corn, onion, garlic, cilantro, queso fresco', 'Andean comfort in a bowl.'],

  ['Plov', 'Uzbek', 72, 'rice, lamb, carrot, onion, cumin, garlic, chickpeas, vegetable oil, raisins', 'Rice cooked in a vast kazan for weddings.'],
  ['Samsa', 'Uzbek', 58, 'flour, lamb, onion, cumin, butter, sesame', 'Tandoor-baked meat pastries.'],
  ['Lagman', 'Uzbek', 56, 'noodles, beef, bell pepper, tomato, onion, garlic, radish, cumin', 'Hand-pulled noodles with a rich stew.'],
  ['Shashlik', 'Uzbek', 60, 'lamb, onion, vinegar, cumin, coriander', 'Silk Road skewers over vine-wood coals.'],

  ['Mohinga', 'Burmese', 60, 'noodles, fish, lemongrass, chickpeas, onion, garlic, ginger, fish sauce, egg, lime', 'Fish and rice-noodle soup, the national breakfast.'],
  ['Lahpet Thoke', 'Burmese', 54, 'tea, cabbage, tomato, peanut, sesame, garlic, chili, lime, fish sauce', 'Fermented tea leaf salad with crunchy beans.'],
  ['Shan Noodles', 'Burmese', 50, 'noodles, chicken, tomato, garlic, peanut, soy sauce, chili, scallion', 'Sticky rice noodles in a tomato-chicken sauce.'],
  ['Ohn No Khao Swè', 'Burmese', 48, 'noodles, chicken, coconut milk, chickpeas, onion, garlic, turmeric, egg, lime, chili', 'Coconut chicken noodle soup.'],

  ['Momo', 'Nepali', 72, 'flour, beef, onion, garlic, ginger, cilantro, cumin, tomato, chili, sesame', 'Pleated dumplings with a fiery tomato achar.'],
  ['Dal Bhat', 'Nepali', 66, 'lentils, rice, turmeric, cumin, garlic, ginger, ghee, spinach, tomato', '"Dal bhat power, 24 hour."'],
  ['Sel Roti', 'Nepali', 46, 'rice, sugar, ghee, banana, cardamom', 'Ring-shaped festival bread.'],
  ['Thukpa', 'Nepali', 54, 'noodles, chicken, carrot, cabbage, garlic, ginger, tomato, chili, cilantro', 'Himalayan noodle soup.'],

  ['Bobotie', 'South African', 58, 'beef, bread, milk, egg, onion, garlic, turmeric, raisins, apricot, bay leaf, almond', 'Spiced mince baked under a savoury custard.'],
  ['Bunny Chow', 'South African', 60, 'bread, chicken, potato, tomato, onion, garlic, ginger, garam masala, chili, curry leaves', 'Durban curry served in a hollowed loaf.'],
  ['Boerewors', 'South African', 56, 'sausage, coriander, cloves, nutmeg, vinegar', 'Coiled farmer’s sausage for the braai.'],
  ['Chakalaka', 'South African', 48, 'beans, carrot, bell pepper, onion, tomato, chili, garlic, ginger, turmeric', 'Spicy township relish.'],
  ['Malva Pudding', 'South African', 52, 'flour, sugar, egg, butter, apricot, milk, cream, vinegar', 'Sticky apricot sponge with hot cream sauce.'],
  ['Biltong', 'South African', 58, 'beef, vinegar, coriander, salt, black pepper', 'Air-dried, spice-cured beef.'],

  ['Poutine', 'Canadian', 76, 'potato, cheese curds, stock, butter, flour, vegetable oil', 'Fries, squeaky curds and gravy.'],
  ['Butter Tarts', 'Canadian', 58, 'flour, butter, sugar, maple syrup, egg, raisins', 'Runny, buttery and fiercely debated.'],
  ['Tourtière', 'Canadian', 50, 'flour, butter, pork, beef, onion, potato, cinnamon, cloves, allspice', 'Québécois spiced meat pie for Christmas Eve.'],
  ['Nanaimo Bars', 'Canadian', 54, 'cocoa, butter, sugar, egg, coconut, walnut, milk, chocolate', 'No-bake three-layer bars.'],
  ['Maple-Glazed Salmon', 'Canadian', 56, 'salmon, maple syrup, soy sauce, garlic, mustard', 'West-coast salmon with a sweet glaze.'],
  ['Blueberry Pie', 'Canadian', 52, 'blueberry, flour, butter, sugar, lemon', 'Wild Maritime blueberries under a lattice.'],

  ['Pastel de Choclo', 'Chilean', 58, 'corn, beef, onion, egg, olive, raisins, chicken, basil, cumin, paprika', 'Sweet-corn crust over a spiced filling.'],
  ['Cazuela', 'Chilean', 52, 'chicken, potato, pumpkin, corn, rice, green beans, carrot, cilantro', 'A clear soup with a bit of everything.'],
  ['Empanadas de Pino', 'Chilean', 60, 'flour, beef, onion, egg, olive, raisins, cumin, paprika', 'Baked turnovers for Fiestas Patrias.'],
  ['Sopaipillas', 'Chilean', 50, 'pumpkin, flour, butter, salt, vegetable oil', 'Pumpkin fritters for rainy days.'],
  ['Completo', 'Chilean', 54, 'bread, sausage, avocado, tomato, mayonnaise', 'A hot dog buried in avocado.'],
];

export const DISHES = D.map(([name, cuisine, popularity, ingr, note], id) => ({
  id,
  name,
  cuisine,
  popularity,
  note,
  ingredients: ingr.split(',').map((s) => s.trim()),
}));

for (const d of DISHES) {
  for (const i of d.ingredients) {
    if (!INGREDIENT_CATEGORY[i]) console.warn('Uncategorised ingredient:', i, 'in', d.name);
  }
}
